version: "3.2"
services:
  <server>:
    build:
      dockerfile: config/docker/Dockerfile.dev
    # depends_on:
    #   - db
  db:
    image: postgres
    container_name: $DB_CONTAINER_NAME
    network_mode: "service:<server>"
    environment:
      - DB_CONTAINER_NAME=${DB_CONTAINER_NAME}
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=ThriveHive10
      - POSTGRES_DB=$APPLICATION
    # ports:
    #   - "5432: 5432"
